"""add usage rollup index

Revision ID: b42b7676ffa5
Revises: f3f66778feab
Create Date: 2026-08-30 00:55:42.042380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42b7676ffa5'
down_revision: Union[str, Sequence[str], None] = 'f3f66778feab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usage_events_tenant_created', 'usage_events', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_tenant_created', table_name='usage_events')
    # ### end Alembic commands ###
