"""add api call metering

Revision ID: f3f66778feab
Revises: 3fe6111b1acb
Create Date: 2026-08-30 00:34:43.638387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f66778feab'
down_revision: Union[str, Sequence[str], None] = '3fe6111b1acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'usage_events',
        sa.Column(
            'api_calls',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('1'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'api_calls')
    # ### end Alembic commands ###
